### ISSUE TITLE
Logging pods are restarted multiple times 

### ISSUE THREAD

**Issue by vbottu** [splunk/splunk-connect-for-kubernetes#413]
**What happened**: Logiging pods are restarting multiple times with the below error
```
#<Thread:0x0000558a7b4a6d38@/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:43:in `rescue in set_up_pod_thread': undefined method `<' for nil:NilClass (NoMethodError)
        from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:38:in `set_up_pod_thread'
        from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274:in `block in configure'
Unexpected error undefined method `<' for nil:NilClass
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:43:in `rescue in set_up_pod_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:38:in `set_up_pod_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.5/lib/fluent/plugin/filter_kubernetes_metadata.rb:274:in `block in configure'

```
**What you expected to happen**:
Pods to run without any restarts
**How to reproduce it (as minimally and precisely as possible)**:
Deployed using 1.4.1 version and seeing this error
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.5
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):red hat 7
- Splunk version: 7.3.3
- Others:

**Comment by rockb1017** [comment]
it seems similar to know bug with that plugin 2.4.5.
we are working on another release with upgraded plugin version. 
in the mean time, please feel free to build docker image from https://github.com/splunk/fluent-plugin-splunk-hec yourself. you can just use `develop` branch and run `make docker` command.

**Comment by vbottu** [comment]
I see that there is a release 1.2.3 ,does it have the upgraded plugin?

**Comment by vbottu** [comment]
I have built the image locally as sugested and pods are restarting with the below error
 ```
Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.Error while watching pods: too old resource version: 68996130 (68999805)
#<Thread:0x000055ec8089f770@/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:276 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:64:in `rescue in set_up_pod_thread': Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting. (Fluent::UnrecoverableError)
        from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:39:in `set_up_pod_thread'
        from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:276:in `block in configure'
Unexpected error Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:64:in `rescue in set_up_pod_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:39:in `set_up_pod_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:276:in `block in configure'
```

**Comment by vbottu** [comment]
Is there any workaround for this issue? I have tried the above solution by building the fluentd-plugin-splunk-hec image locally and   the pods are still restarted multiple times with the above error

**Comment by matthewmodestino** [comment]
1.4.2 is out! please test! My other customers seem to have seen positive results! let us know how it goes!

**Comment by vbottu** [comment]
Thank you @matthewmodestino , is there any ideal chunk limit size to avoid data loss?

**Comment by matthewmodestino** [comment]
Hard to say, as they are not directly linked, unless you are sending events bigger than the chunk limit, which I doubt.  If you are stop it :)

Data loss is mostly governed by the buffers and retry parameters on the fluentd side, as well as the tail processor on fluentd being able to keep up with file rotation on node. 

No real silver bullet, but by analyzing the collector in Dev you can get a nicely optimized confg. I highly recommend using the splunk app called "trackme" to help analyze. 

Are you struggling with data loss?

What are your buffer and retry settings?

**Comment by vbottu** [comment]
I've deployed 1.4.2 with the default buffer and retry settings, will let you know if I observe any data loss with those settings.

**Comment by vbottu** [comment]
1.4.2 has been running for 4 days and there are some pod restarts ,this time I've used the default configuration.I am seeing the below error

```
[error]: Exception encountered parsing namespace watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.Error while watching namespaces: too old resource version: 90626824 (93155360)
#<Thread:0x00005639b0d90f90@/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/filter_kubernetes_metadata.rb:279 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:64:in `rescue in set_up_namespace_thread': Exception encountered parsing namespace watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting. (Fluent::UnrecoverableError)
        from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:39:in `set_up_namespace_thread'
        from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/filter_kubernetes_metadata.rb:279:in `block in configure'
Unexpected error Exception encountered parsing namespace watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:64:in `rescue in set_up_namespace_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:39:in `set_up_namespace_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/filter_kubernetes_metadata.rb:279:in `block in configure'
```

**Comment by rockb1017** [comment]
@vbottu Thank you for letting us know. could you share how many restart it was during 4 days?

**Comment by rockb1017** [comment]
aha. i found out why. it was only partially fixed. (handled watching pods, but not watching namespace) 
I will release new version with fix.

**Comment by vbottu** [comment]
@rockb1017 , thank you , do you need any information from me?

**Comment by rockb1017** [comment]
I just pushed new image for testing. `rock1017/fluentd-hec:1.2.4-1` 
Could you use this image and see if it is resolved?

**Comment by vbottu** [comment]
Sure, will try it out and get back to you. Thanks

**Comment by vbottu** [comment]
It looks as of now, no restarts were observed

**Comment by rockb1017** [comment]
Awesome! Thank you! 
it is officially released btw. SCK 1.4.3
`splunk/fluentd-hec:1.2.4`

**Comment by vbottu** [comment]
#467
